// AUTO-GENERATED by scripts/pull-assets.mjs — real LEC photos from leclaser.com.
export const LOGO = { src: "/brand/logo.png", width: 200, height: 73 };
export const ICON = "/brand/icon.png";

export const PORTFOLIO_IMAGES: Record<string, string[]> = {
  "svjetlece-reklame-logotipi": [
    "/portfolio/svjetlece-reklame-logotipi/01.jpg",
    "/portfolio/svjetlece-reklame-logotipi/02.jpg",
    "/portfolio/svjetlece-reklame-logotipi/03.jpg",
    "/portfolio/svjetlece-reklame-logotipi/04.jpg",
    "/portfolio/svjetlece-reklame-logotipi/05.jpg",
    "/portfolio/svjetlece-reklame-logotipi/06.jpg",
    "/portfolio/svjetlece-reklame-logotipi/07.jpg",
    "/portfolio/svjetlece-reklame-logotipi/08.jpg",
    "/portfolio/svjetlece-reklame-logotipi/09.jpg",
    "/portfolio/svjetlece-reklame-logotipi/10.jpg"
  ],
  "reklamne-table-totemi": [
    "/portfolio/reklamne-table-totemi/01.jpg",
    "/portfolio/reklamne-table-totemi/02.jpg",
    "/portfolio/reklamne-table-totemi/03.jpg",
    "/portfolio/reklamne-table-totemi/04.jpg",
    "/portfolio/reklamne-table-totemi/05.jpg",
    "/portfolio/reklamne-table-totemi/06.jpg",
    "/portfolio/reklamne-table-totemi/07.jpg",
    "/portfolio/reklamne-table-totemi/08.jpg",
    "/portfolio/reklamne-table-totemi/09.jpg",
    "/portfolio/reklamne-table-totemi/10.jpg"
  ],
  "hotelske-oznake-wayfinding": [
    "/portfolio/hotelske-oznake-wayfinding/01.jpg",
    "/portfolio/hotelske-oznake-wayfinding/02.jpg",
    "/portfolio/hotelske-oznake-wayfinding/03.jpg",
    "/portfolio/hotelske-oznake-wayfinding/04.jpg",
    "/portfolio/hotelske-oznake-wayfinding/05.jpg",
    "/portfolio/hotelske-oznake-wayfinding/06.jpg",
    "/portfolio/hotelske-oznake-wayfinding/07.jpg",
    "/portfolio/hotelske-oznake-wayfinding/08.jpg",
    "/portfolio/hotelske-oznake-wayfinding/09.jpg"
  ],
  "pos-displeji": [
    "/portfolio/pos-displeji/01.jpg",
    "/portfolio/pos-displeji/02.jpg",
    "/portfolio/pos-displeji/03.jpg",
    "/portfolio/pos-displeji/04.jpg",
    "/portfolio/pos-displeji/05.jpg",
    "/portfolio/pos-displeji/06.jpg",
    "/portfolio/pos-displeji/07.jpg",
    "/portfolio/pos-displeji/08.jpg",
    "/portfolio/pos-displeji/09.jpg",
    "/portfolio/pos-displeji/10.jpg"
  ],
  "pleksiglas-proizvodi": [
    "/portfolio/pleksiglas-proizvodi/01.jpg",
    "/portfolio/pleksiglas-proizvodi/02.jpg",
    "/portfolio/pleksiglas-proizvodi/03.jpg",
    "/portfolio/pleksiglas-proizvodi/04.jpg",
    "/portfolio/pleksiglas-proizvodi/05.jpg",
    "/portfolio/pleksiglas-proizvodi/06.jpg",
    "/portfolio/pleksiglas-proizvodi/07.jpg",
    "/portfolio/pleksiglas-proizvodi/08.jpg",
    "/portfolio/pleksiglas-proizvodi/09.jpg",
    "/portfolio/pleksiglas-proizvodi/10.jpg"
  ],
  "enterijer-eksterijer": [
    "/portfolio/enterijer-eksterijer/01.jpg",
    "/portfolio/enterijer-eksterijer/02.jpg",
    "/portfolio/enterijer-eksterijer/03.jpg",
    "/portfolio/enterijer-eksterijer/04.jpg",
    "/portfolio/enterijer-eksterijer/05.jpg",
    "/portfolio/enterijer-eksterijer/06.jpg",
    "/portfolio/enterijer-eksterijer/07.jpg",
    "/portfolio/enterijer-eksterijer/08.jpg",
    "/portfolio/enterijer-eksterijer/09.jpg",
    "/portfolio/enterijer-eksterijer/10.jpg"
  ]
};

export const SERVICE_IMAGES: Record<string, string[]> = {
  "lasersko-rezanje": [
    "/services/lasersko-rezanje/01.jpg",
    "/services/lasersko-rezanje/02.jpg",
    "/services/lasersko-rezanje/03.jpg",
    "/services/lasersko-rezanje/04.jpg"
  ],
  "lasersko-graviranje": [
    "/services/lasersko-graviranje/01.jpg"
  ],
  "cnc-rezanje-glodanje": [
    "/services/cnc-rezanje-glodanje/01.jpg",
    "/services/cnc-rezanje-glodanje/02.jpg",
    "/services/cnc-rezanje-glodanje/03.jpg",
    "/services/cnc-rezanje-glodanje/04.jpg"
  ],
  "dijamantsko-poliranje": [
    "/services/dijamantsko-poliranje/01.jpg",
    "/services/dijamantsko-poliranje/02.jpg",
    "/services/dijamantsko-poliranje/03.jpg"
  ],
  "termo-savijanje-lijepljenje": [
    "/services/termo-savijanje-lijepljenje/01.jpg",
    "/services/termo-savijanje-lijepljenje/02.jpg",
    "/services/termo-savijanje-lijepljenje/03.jpg",
    "/services/termo-savijanje-lijepljenje/04.jpg",
    "/services/termo-savijanje-lijepljenje/05.jpg",
    "/services/termo-savijanje-lijepljenje/06.jpg"
  ],
  "dizajn-proizvoda": [
    "/services/dizajn-proizvoda/01.jpg",
    "/services/dizajn-proizvoda/02.jpg",
    "/services/dizajn-proizvoda/03.jpg",
    "/services/dizajn-proizvoda/04.jpg",
    "/services/dizajn-proizvoda/05.jpg",
    "/services/dizajn-proizvoda/06.jpg"
  ]
};

export function categoryImages(slug: string): string[] { return PORTFOLIO_IMAGES[slug] || []; }
export function categoryHero(slug: string): string | null { return (PORTFOLIO_IMAGES[slug] || [])[0] || null; }
export function serviceImages(slug: string): string[] { return SERVICE_IMAGES[slug] || []; }
export function serviceHero(slug: string): string | null { return (SERVICE_IMAGES[slug] || [])[0] || null; }
